export const paths = {
  home: '/',
  balance: '/balance',
  hajira: '/hajira',
  cash: '/cash',
  others: '/others',
  sites: '/sites',
  siteDetail: (id) => `/sites/${id}`,
  users: '/users',
  userDetail: (id) => `/users/${id}`,
  labours: '/labours',
  labourDetail: (id) => `/labours/${id}`,
  labourSessionRecords: (labourId, sessionId) =>
    `/labours/${labourId}/sessions/${sessionId}/records`,
  appInfo: '/app-info',
  activities: '/activities',
  login: '/login',
  register: '/register',
  registerConfirm: '/register/confirm',
  passwordReset: '/password/reset',
  passwordResetConfirm: '/password/reset/confirm',
  profile: '/profile',
}
