export const paths = {
  home: '/',
  balance: '/balance',
  hajira: '/hajira',
  cash: '/cash',
  others: '/others',
  sites: '/sites',
  siteNew: '/sites/new',
  siteDetail: (id) => `/sites/${id}`,
  siteBilling: (id) => `/sites/${id}/billing`,
  sitePrivateCash: (id) => `/sites/${id}/private-cash`,
  users: '/users',
  userNew: '/users/new',
  userDetail: (id) => `/users/${id}`,
  labours: '/labours',
  labourNew: '/labours/new',
  labourDetail: (id) => `/labours/${id}`,
  labourSessions: (labourId) => `/labours/${labourId}/sessions`,
  labourSessionDetail: (labourId, sessionId) =>
    `/labours/${labourId}/sessions/${sessionId}`,
  labourSessionRecords: (labourId, sessionId) =>
    `/labours/${labourId}/sessions/${sessionId}/records`,
  labourRunningSession: (labourId) => `/labours/${labourId}/sessions/running`,
  labourLatestSession: (labourId) => `/labours/${labourId}/sessions/latest`,
  appInfo: '/app-info',
  activities: '/activities',
  login: '/login',
  register: '/register',
  registerConfirm: '/register/confirm',
  passwordReset: '/password/reset',
  passwordResetConfirm: '/password/reset/confirm',
  profile: '/profile',
}
