export const paths = {
  home: '/',
  balance: '/balance',
  hajira: '/hajira',
  cash: '/cash',
  cashNew: '/cash/new',
  cashDetail: (id) => `/cash/${id}`,
  others: '/others',
  login: '/login',
  register: '/register',
  registerConfirm: '/register/confirm',
  passwordReset: '/password/reset',
  passwordResetConfirm: '/password/reset/confirm',
  profile: '/profile',
  changePassword: '/profile/password',
}
